### ISSUE TITLE
White background behind text on home page.

### ISSUE THREAD

**Issue by Dronf3** [katelyynn/bleh#5]
I also found this. I'm not sure if it is supposed to be like that or not, but it looks very out of place.
![image](https://github.com/katelyynn/bleh/assets/114812232/abd979a8-5223-430b-89c8-87d9722b6472)

**Comment by katelyynn** [comment]
yea thats on the backlog of things i need to do, prolly should prioritise tbh since its the home page but oh well 😭

usually u will see this in the bottom right if a page is incomplete (i forgot it here evidently oops)
![image](https://github.com/katelyynn/bleh/assets/46572320/0e60b897-9884-48c0-a7bb-ac73122941a4)

**Comment by katelyynn** [comment]
(fixed via https://github.com/katelyynn/bleh/pull/6)

> it's not exactly what i envisioned but this is kind of a hassle to work with so for now if it works it works. any suggestions will b welcome tho especially on the lower artist similarity text

**Comment by Dronf3** [comment]
it looks pretty coo,l you cant click on the recommendations though lol
